"""
Conjunction Data Message (CDM) Generator — CCSDS 508.0-B-1 Format

Generates CDMs in the Key-Value Notation (KVN) format defined by
the Consultative Committee for Space Data Systems (CCSDS).

CDMs are the universal interchange format for conjunction events,
used by the 18th SDS, NASA CARA, ESA, LeoLabs, and all major
SSA providers.

Reference: CCSDS 508.0-B-1 "Conjunction Data Message" (June 2013)
"""

from datetime import datetime
from typing import Optional


def generate_cdm(
    approach,
    primary_omm=None,
    secondary_omm=None,
    originator: str = "GODS_EYE_SSA",
    message_id: str = None,
) -> dict:
    """
    Generate a CDM structure from a CloseApproach object.

    Args:
        approach: CloseApproach dataclass instance
        primary_omm: OMMRecord of primary (optional, for extra metadata)
        secondary_omm: OMMRecord of secondary (optional)
        originator: Organization generating the CDM
        message_id: Unique message ID (auto-generated if None)

    Returns:
        Dict with all CDM fields
    """
    now = datetime.utcnow()
    if message_id is None:
        message_id = f"GE-{now.strftime('%Y%m%d%H%M%S')}-{approach.primary_norad_id}-{approach.secondary_norad_id}"

    cdm = {
        # Header
        "CCSDS_CDM_VERS": "1.0",
        "CREATION_DATE": now.strftime("%Y-%m-%dT%H:%M:%S.000"),
        "ORIGINATOR": originator,
        "MESSAGE_FOR": f"{approach.primary_name}",
        "MESSAGE_ID": message_id,

        # Relative metadata
        "TCA": approach.tca,
        "MISS_DISTANCE": round(approach.miss_distance_km * 1000.0, 1),  # meters
        "MISS_DISTANCE_UNIT": "m",
        "RELATIVE_SPEED": round(approach.relative_velocity_km_s * 1000.0, 1),  # m/s
        "RELATIVE_SPEED_UNIT": "m/s",
        "RELATIVE_POSITION_R": round(approach.radial_km * 1000.0, 1),
        "RELATIVE_POSITION_T": round(approach.in_track_km * 1000.0, 1),
        "RELATIVE_POSITION_N": round(approach.cross_track_km * 1000.0, 1),

        # Collision probability
        "COLLISION_PROBABILITY": getattr(approach, 'collision_probability', None),
        "COLLISION_PROBABILITY_METHOD": "CHAN-2D",

        # Object 1 (Primary)
        "OBJECT1_DESIGNATOR": str(approach.primary_norad_id),
        "OBJECT1_NAME": approach.primary_name,
        "OBJECT1_CATALOG_NAME": "SATCAT",
        "OBJECT1_OBJECT_TYPE": _infer_object_type(approach.primary_name),

        # Object 2 (Secondary)
        "OBJECT2_DESIGNATOR": str(approach.secondary_norad_id),
        "OBJECT2_NAME": approach.secondary_name,
        "OBJECT2_CATALOG_NAME": "SATCAT",
        "OBJECT2_OBJECT_TYPE": _infer_object_type(approach.secondary_name),
    }

    # Add orbital metadata if OMMs are available
    if primary_omm:
        cdm.update({
            "OBJECT1_INTERNATIONAL_DESIGNATOR": getattr(primary_omm, 'object_id', ''),
            "OBJECT1_EPHEMERIS_NAME": "SGP4",
            "OBJECT1_COVARIANCE_METHOD": "ESTIMATED",
            "OBJECT1_SEMI_MAJOR_AXIS": round(getattr(primary_omm, 'semimajor_axis_km', 0), 3),
            "OBJECT1_ECCENTRICITY": getattr(primary_omm, 'eccentricity', 0),
            "OBJECT1_INCLINATION": round(getattr(primary_omm, 'inclination', 0), 4),
            "OBJECT1_PERIAPSIS_ALTITUDE": round(getattr(primary_omm, 'periapsis_km', 0), 3),
            "OBJECT1_APOAPSIS_ALTITUDE": round(getattr(primary_omm, 'apoapsis_km', 0), 3),
        })

    if secondary_omm:
        cdm.update({
            "OBJECT2_INTERNATIONAL_DESIGNATOR": getattr(secondary_omm, 'object_id', ''),
            "OBJECT2_EPHEMERIS_NAME": "SGP4",
            "OBJECT2_COVARIANCE_METHOD": "ESTIMATED",
            "OBJECT2_SEMI_MAJOR_AXIS": round(getattr(secondary_omm, 'semimajor_axis_km', 0), 3),
            "OBJECT2_ECCENTRICITY": getattr(secondary_omm, 'eccentricity', 0),
            "OBJECT2_INCLINATION": round(getattr(secondary_omm, 'inclination', 0), 4),
            "OBJECT2_PERIAPSIS_ALTITUDE": round(getattr(secondary_omm, 'periapsis_km', 0), 3),
            "OBJECT2_APOAPSIS_ALTITUDE": round(getattr(secondary_omm, 'apoapsis_km', 0), 3),
        })

    return cdm


def format_cdm_kvn(cdm: dict) -> str:
    """
    Format a CDM dict into CCSDS Key-Value Notation (KVN) text.

    This is the standard text format for CDM interchange.

    Args:
        cdm: CDM dictionary from generate_cdm()

    Returns:
        CDM as a KVN-formatted string
    """
    lines = []
    lines.append(f"CCSDS_CDM_VERS                = {cdm.get('CCSDS_CDM_VERS', '1.0')}")
    lines.append(f"COMMENT  Generated by God's Eye SSA Platform")
    lines.append(f"CREATION_DATE                  = {cdm['CREATION_DATE']}")
    lines.append(f"ORIGINATOR                     = {cdm['ORIGINATOR']}")
    lines.append(f"MESSAGE_FOR                    = {cdm['MESSAGE_FOR']}")
    lines.append(f"MESSAGE_ID                     = {cdm['MESSAGE_ID']}")
    lines.append("")

    # Relative metadata
    lines.append(f"TCA                            = {cdm['TCA']}")
    lines.append(f"MISS_DISTANCE                  = {cdm['MISS_DISTANCE']} [m]")
    lines.append(f"RELATIVE_SPEED                 = {cdm['RELATIVE_SPEED']} [m/s]")
    lines.append(f"RELATIVE_POSITION_R            = {cdm['RELATIVE_POSITION_R']} [m]")
    lines.append(f"RELATIVE_POSITION_T            = {cdm['RELATIVE_POSITION_T']} [m]")
    lines.append(f"RELATIVE_POSITION_N            = {cdm['RELATIVE_POSITION_N']} [m]")

    pc = cdm.get('COLLISION_PROBABILITY')
    if pc is not None:
        lines.append(f"COLLISION_PROBABILITY          = {pc:.6e}")
        lines.append(f"COLLISION_PROBABILITY_METHOD   = {cdm.get('COLLISION_PROBABILITY_METHOD', 'CHAN-2D')}")
    lines.append("")

    # Object 1
    lines.append("OBJECT                         = OBJECT1")
    lines.append(f"OBJECT_DESIGNATOR              = {cdm['OBJECT1_DESIGNATOR']}")
    lines.append(f"CATALOG_NAME                   = {cdm.get('OBJECT1_CATALOG_NAME', 'SATCAT')}")
    lines.append(f"OBJECT_NAME                    = {cdm['OBJECT1_NAME']}")
    if cdm.get('OBJECT1_INTERNATIONAL_DESIGNATOR'):
        lines.append(f"INTERNATIONAL_DESIGNATOR       = {cdm['OBJECT1_INTERNATIONAL_DESIGNATOR']}")
    lines.append(f"OBJECT_TYPE                    = {cdm.get('OBJECT1_OBJECT_TYPE', 'PAYLOAD')}")
    lines.append(f"EPHEMERIS_NAME                 = {cdm.get('OBJECT1_EPHEMERIS_NAME', 'SGP4')}")
    lines.append(f"COVARIANCE_METHOD              = {cdm.get('OBJECT1_COVARIANCE_METHOD', 'ESTIMATED')}")
    if cdm.get('OBJECT1_SEMI_MAJOR_AXIS'):
        lines.append(f"SEMI_MAJOR_AXIS                = {cdm['OBJECT1_SEMI_MAJOR_AXIS']} [km]")
        lines.append(f"ECCENTRICITY                   = {cdm['OBJECT1_ECCENTRICITY']}")
        lines.append(f"INCLINATION                    = {cdm['OBJECT1_INCLINATION']} [deg]")
        lines.append(f"PERIAPSIS_ALTITUDE             = {cdm['OBJECT1_PERIAPSIS_ALTITUDE']} [km]")
        lines.append(f"APOAPSIS_ALTITUDE              = {cdm['OBJECT1_APOAPSIS_ALTITUDE']} [km]")
    lines.append("")

    # Object 2
    lines.append("OBJECT                         = OBJECT2")
    lines.append(f"OBJECT_DESIGNATOR              = {cdm['OBJECT2_DESIGNATOR']}")
    lines.append(f"CATALOG_NAME                   = {cdm.get('OBJECT2_CATALOG_NAME', 'SATCAT')}")
    lines.append(f"OBJECT_NAME                    = {cdm['OBJECT2_NAME']}")
    if cdm.get('OBJECT2_INTERNATIONAL_DESIGNATOR'):
        lines.append(f"INTERNATIONAL_DESIGNATOR       = {cdm['OBJECT2_INTERNATIONAL_DESIGNATOR']}")
    lines.append(f"OBJECT_TYPE                    = {cdm.get('OBJECT2_OBJECT_TYPE', 'PAYLOAD')}")
    lines.append(f"EPHEMERIS_NAME                 = {cdm.get('OBJECT2_EPHEMERIS_NAME', 'SGP4')}")
    lines.append(f"COVARIANCE_METHOD              = {cdm.get('OBJECT2_COVARIANCE_METHOD', 'ESTIMATED')}")
    if cdm.get('OBJECT2_SEMI_MAJOR_AXIS'):
        lines.append(f"SEMI_MAJOR_AXIS                = {cdm['OBJECT2_SEMI_MAJOR_AXIS']} [km]")
        lines.append(f"ECCENTRICITY                   = {cdm['OBJECT2_ECCENTRICITY']}")
        lines.append(f"INCLINATION                    = {cdm['OBJECT2_INCLINATION']} [deg]")
        lines.append(f"PERIAPSIS_ALTITUDE             = {cdm['OBJECT2_PERIAPSIS_ALTITUDE']} [km]")
        lines.append(f"APOAPSIS_ALTITUDE              = {cdm['OBJECT2_APOAPSIS_ALTITUDE']} [km]")

    return "\n".join(lines)


def _infer_object_type(name: str) -> str:
    """Infer CCSDS object type from object name."""
    name_upper = name.upper()
    if "DEB" in name_upper:
        return "DEBRIS"
    elif "R/B" in name_upper:
        return "ROCKET BODY"
    else:
        return "PAYLOAD"
